driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: debian-8.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
    driver_config:
      disable_upstart: false

suites:
  - name: default
    run_list:
      - recipe[vault::default]
    attributes:
  - name: server
    run_list:
      - recipe[vault::default]
    attributes:
      vault:
        mode: server
